language: python
python:
  - 2.7
notifications:
  email:
    - chaturanga50@gmail.com
install:
  - pip install pycodestyle
  - python setup.py install
env:
  - BOTO_CONFIG=/tmp/nowhere
script:
  - "pycodestyle --ignore=E501,E225,W293,E731,W292 modules"